#!/usr/bin/bash
########################################################################
# Begin localnet
#
# Description : Loopback device
#
# Authors     : Gerard Beekmans  - gerard@linuxfromscratch.org
#               DJ Lucas - dj@linuxfromscratch.org
# Update      : Bruce Dubbs - bdubbs@linuxfromscratch.org
#
# Version     : LFS 7.0
#
########################################################################

### BEGIN INIT INFO
# Provides:            localnet
# Required-Start:      $local_fs
# Should-Start:
# Required-Stop:
# Should-Stop:
# Default-Start:       S
# Default-Stop:        0 6
# Short-Description:   Starts the local network.
# Description:         Sets the hostname of the machine and starts the
#                      loopback interface.
# X-LFS-Provided-By:   LFS
### END INIT INFO

. /etc/rc.d/init.d/init-functions

[ -r /usr/etc/sysconfig/hostname ] && export HOSTNAME=$(/usr/bin/cat /usr/etc/sysconfig/hostname) 
[ -r /usr/etc/sysconfig/network ] && source /usr/etc/sysconfig/network


case "${1}" in
   start)
      log_info_msg "Bringing up the loopback interface..."
      /usr/sbin/ip addr add 127.0.0.1/8 label lo dev lo
      /usr/sbin/ip link set lo up
      evaluate_retval

      log_info_msg "Setting hostname to ${HOSTNAME}..."
      /usr/bin/hostname ${HOSTNAME}
      evaluate_retval
      ;;

   stop)
      log_info_msg "Bringing down the loopback interface..."
      /usr/sbin/ip link set lo down
      evaluate_retval
      ;;

   restart)
      ${0} stop
      sleep 2
      ${0} start
      ;;

   status)
      echo "Hostname is: $(hostname)"
      /usr/sbin/ip link show lo
      ;;

   *)
      echo "Usage: ${0} {start|stop|restart|status}"
      exit 1
      ;;
esac

exit 0

# End localnet
